### ISSUE TITLE
Payments not working

### ISSUE THREAD

**Issue by pupasani** [nicolasgomollon/AppSales-Mobile#14]
Even with the latest update payments are still not downloading. If it makes a difference, I have a single account with several products.

**Comment by nicolasgomollon** [comment]
It looks like one of the API calls that AppSales relies on to fetch an important component for the payment downloads is down (#10).

I’m getting a `503: Service Temporarily Unavailable` for `https://reportingitc2.apple.com/api/user/info`.

I just took another look at the API calls made when accessing the “Payments & Financial Reports” page in iTunes Connect, and realized there’s a secondary equivalent API call at `https://itunesconnect.apple.com/WebObjects/iTunesConnect.woa/ra/user/detail`.

Give me a second to make the necessary changes and push the changes to the repo.

**Comment by pupasani** [comment]
Thank you! One issue, it crashes when updating the payments badge - see attached screenshot.

![exception](https://cloud.githubusercontent.com/assets/118981/15345936/17bf2a7e-1c68-11e6-88de-c2211dd0b515.png)

**Comment by Morpheus2002** [comment]
After the fix all payments for 2016 are downloaded as 0 Values.

![img_2372](https://cloud.githubusercontent.com/assets/3219136/15647991/b4f7bf6e-2667-11e6-9abc-14ff56a2c0c0.PNG)
