### ISSUE TITLE
App crashes after payments download

### ISSUE THREAD

**Issue by pupasani** [nicolasgomollon/AppSales-Mobile#15]
Its downloading the payments successfully, but looks like its crashing when trying to update the payments badge:

![paymentscrash](https://cloud.githubusercontent.com/assets/118981/15788929/9fabbe66-297e-11e6-86d6-9fe0c2d98e0b.png)

**Comment by paulfowler** [comment]
Me too - but all looks ok after re-starting the app.

**Comment by sirnacnud** [comment]
This is fixed in #26.
