### ISSUE TITLE
No reports download

### ISSUE THREAD

**Issue by Morpheus2002** [nicolasgomollon/AppSales-Mobile#16]
Since 3 days I can't download any sales reports. Anyone experiencing the same issue?

**Comment by ddaddy** [comment]
It's working fine for me.
Have you entered an app specific password?

**Comment by paulfowler** [comment]
What is this app specific password thing anyway - i cannot work it out

**Comment by paulfowler** [comment]
What is this app specific password thing anyway - i cannot work it out - i use a finance user, which has access to all apps, so does not have app specificity.

**Comment by ddaddy** [comment]
It's 2 factor Auth I think. I just set it to my iTC password and it works.

**Comment by paulfowler** [comment]
Thanks that works for me now - confusing - and that button thing does not make it any clearer.

**Comment by Morpheus2002** [comment]
The problem was on my side. I recently upgraded my ITC account to corporate account and Apple changed the vendor ID. I just fetched the new one and everything works fine. Sorry guys.
