### ISSUE TITLE
Access to the colour picker on ios8.4.1 denied

### ISSUE THREAD

**Issue by paulfowler** [nicolasgomollon/AppSales-Mobile#17]
In the 9.3 simulator i can swipe a product cell left to reveal EDIT.
But on a real device (iPhone 5 running iOS 8.4.1) i cannot.
v.frustrating
Suggestions ?

**Comment by nicolasgomollon** [comment]
It’s assumed that the users of this app are developers running the latest versions of iOS. I also don’t have any test devices with that version of iOS, but all devices running iOS 8 are capable of running iOS 9 anyway (http://iossupportmatrix.com/).

For this reason, I don’t think it’s worth the trouble of finding a fix for this. You’re more than welcome to submit a Pull Request if you find a fix yourself.
