### ISSUE TITLE
Ready suggestion

### ISSUE THREAD

**Issue by ddaddy** [nicolasgomollon/AppSales-Mobile#2]
Coming from forks that can simply be downloaded as a full zip file, or checked out and used immediately, could you add to the readme instructions for checking out the dependencies?

ie.

> Navigate to checked out project folder
> git submodule init
> git submodule update

**Comment by nicolasgomollon** [comment]
Done!

**Comment by ddaddy** [comment]
Excellent. I'll mark my fork as deprecated and forward everyone to yours.
