### ISSUE TITLE
ReviewDownloader uses CoreData in an unsafe manner

### ISSUE THREAD

**Issue by sirnacnud** [nicolasgomollon/AppSales-Mobile#21]
I have been running in to some crashes when downloading the reviews for an app, the call stacks indicate something has gone wrong with CoreData.

When I started looking at the code in `ReviewDownloader`, I noticed that both `NSManagedObjects` and the `NSManagedObjectContext` are being created and used in different threads. Neither of these classes are thread safe and can only be used on the same thread they were created from.

I think `ReviewDownloader` needs a fair amount of rework in order to make it use CoreData correctly. I will try to push up a PR if I get time.

**Comment by nicolasgomollon** [comment]
I had no idea those objects were not thread safe. The Reviews API had changed and was no longer working anyway, so I went ahead and updated `ReviewDownloader` to adhere to the new API, as well as refactored parts of it to ensure those objects are used only in the main thread.

Commit a2e26f0d58ec366f22a0e987a7a28b104e55971d takes care of this.

**Comment by sirnacnud** [comment]
See the `Concurrency` section in the [NSManagedObjectContext docs](https://developer.apple.com/documentation/coredata/nsmanagedobjectcontext).
