### ISSUE TITLE
I Get "Your Access Token is invalid"

### ISSUE THREAD

**Issue by TheCrab-xx** [nicolasgomollon/AppSales-Mobile#33]
I get "Your Access Token is invalid"  after generate a new token from iTunesConnect and copied into AppSales. Due this error I can't download new report and payments.

**Comment by nicolasgomollon** [comment]
Have you tried using the `Get Access Token…` or `Generate Access Token…` buttons directly from within AppSales instead of copying and pasting it in from the iTunes Connect website?

**Comment by TheCrab-xx** [comment]
Yes, i tried to generate or get a new token from the app but nothing happens.

**Comment by nicolasgomollon** [comment]
hmmm… that’s a little strange. The app should be giving you at least some kind of feedback. It’s hard to tell what exactly might be going on without some more details.

- Do you get any kind of alert or loading view after tapping those buttons?
- What about any console messages?
- Does the `Auto-Fill Vendor ID…` button work for you?
- Which version of iOS are you using?
- Does your iTunes Connect account use Two-Factor Authentication?
- Do you have more than one vendor or developer account associated with your iTunes Connect account?

**Comment by TheCrab-xx** [comment]
Ok...here are some details

• I don't get any kind of alert after tapping buttons, just loading appear/disappear and nothing happens;
• No console messages shown;
• The Auto-Fill Vendor ID doesn't work, I set the ID manually;
• I'm using iOS 11 version;
• My iTunes Connect have Two-Factor Authentication enabled;
• I have just one developer account set;

I tried to remove and re-install AppSales but nothing changed

![img_952b0efc4499-1](https://user-images.githubusercontent.com/1183097/31482503-e4a51d88-af28-11e7-8857-7727335da4c6.jpeg)

**Comment by TheCrab-xx** [comment]
Tried to logout and login many times and now it works.
It seems that was Apple two step auth problem
