### ISSUE TITLE
October 20th sales will not download

### ISSUE THREAD

**Issue by dave256** [nicolasgomollon/AppSales-Mobile#35]
I don't know if it's something specific to my account, but the Oct 20th sales report will not download and I have a second iOS device that I had not downloaded the sales in a week or two and it won't download anyway of the ones from the last week. The other reports all had downloaded on my main iOS device up until today when I tried to download yesterday's report. The report is available on the App Store Connect website.

**Comment by Morpheus2002** [comment]
Same for me.

**Comment by dave256** [comment]
It must have been something on Apple's end as both 10/20 and 10/21 (and its weekly report) downloaded for me Monday morning 10/22.

**Comment by Morpheus2002** [comment]
Same here.
