### ISSUE TITLE
No reports since 12th

### ISSUE THREAD

**Issue by ddaddy** [nicolasgomollon/AppSales-Mobile#38]
Is anyone else experiencing no reports for the last 4 days?
It can't be a token issue, as it downloaded 2 reports for 10th & 11th Dec, but says none available for last 4 days.
Looking at App Store Connect, there are reports there!

Anyone else?

**Comment by vincechiu** [comment]
Yes, experience the same issue. We’re not alone, App Annie has reported $0 revenue since but iTunesConnect did report some revenue. Something has changed on Apple’s end.

VC

**Comment by ddaddy** [comment]
I've just looked at an OSX app I also use called App Wage, and it has in fact downloaded reports, but they are blank. They have headers, but no actual data.
Downloading from App Store Connect directly gives correct reports.

Odd.

**Comment by Morpheus2002** [comment]
On reports for me too.

**Comment by fixups** [comment]
@ddaddy: Same here.

**Comment by nicolasgomollon** [comment]
Looks like the `gzip` decompression code was faulty, so the reports were downloading just fine, but were not being decompressed properly. I just committed a fix to the repo.

Please check out the latest build 2.4 (677) from commit f19b334d7ff2b7e2bbe2afe4047232cb7315d378 when you guys get the chance.

**Comment by sweetppro** [comment]
The fix is working well,
Thanks
