### ISSUE TITLE
Number of yearly In-App Subscriptions Mac is missing (solution here)

### ISSUE THREAD

**Issue by demodit** [nicolasgomollon/AppSales-Mobile#39]
Adding "IAY-M" to combinedPaidTransactionTypes solves that.

**Comment by ddaddy** [comment]
Thanks. I have added this to a pull request and also added the display of `(Renewable Sub)` instead of it currently showing `(null)`

**Comment by nicolasgomollon** [comment]
Fixed by and merged in #40.
