### ISSUE TITLE
Access Token fix

### ISSUE THREAD

**Issue by ddaddy** [nicolasgomollon/AppSales-Mobile#41]
I issued a pull request to fix Mac subscriptions, but I just updated it (I don't know how to make it a separate pull request, it seems to have just picked up my latest commit too) to fix the Generate and Fetch Access Tokens.

Can you please accept them.

Thanks

**Comment by nicolasgomollon** [comment]
Awesome! I appreciate the time you took to get it working again! _(Merged in #40.)_
