### ISSUE TITLE
Generate Access Token doesn't work anymore

### ISSUE THREAD

**Issue by demodit** [nicolasgomollon/AppSales-Mobile#43]
My token has expired. When using "Generate Access Token" or "Get Access Token" on device or simulator I get an error message.

This is the returned in the dictionary of NSURL request:
        code = GSF01042;
        message = "Security is not configured for the app gsf";

**Comment by ddaddy** [comment]
Same here. I've just proxied logging into AppStoreConnect and the URL `https://reportingitc2.apple.com/gsf/csrftoken` doesn't seem to be called, so either it's been removed or it's part of a different method.
I'm not sure who originally figured that part of the process.

**Comment by ddaddy** [comment]
Ok, I found a place we could grab the CSRF. It's not ideal, but it works.
Take a look the the pull request above.

**Comment by demodit** [comment]
Great! That is working. Many thanks!

**Comment by ddaddy** [comment]
Can we get a pull please @nicolasgomollon

**Comment by nicolasgomollon** [comment]
Sorry, I work Monday through Friday, and don’t always have time to look into this stuff. Thanks for opening this issue and making the Pull Request!
