### ISSUE TITLE
Access Token can not be generated anymore

### ISSUE THREAD

**Issue by demodit** [nicolasgomollon/AppSales-Mobile#49]
Get Access Token and Generate Access Token are throwing following error message:

**Could not fetch CSRF token from server.**

NSURLConnection finished with error - code -1003

**Comment by ddaddy** [comment]
I've spent the morning trying to fix this but i've hit a dead end. @redbug26 pull request retrieves the correct CSRF however fetching the token results in `You do not have access to this application`.

It seems to be a cookie issue, as if I copy proxied Cookies from a web browser session into the request, it works fine.

I'm afraid I don't know much about cookies or how to use them in iOS.

**Comment by nicolasgomollon** [comment]
hmm, ok, I’ll see if I can take a look at what’s going on this weekend. Thanks for the additional details @ddaddy! Also, apologies for being unresponsive and unable to update the app—even though I rely on it every day too.

**Comment by nicolasgomollon** [comment]
Apologies for the delay! It should now be fixed in 2.4.5 (711) @ c872a83072ab4e7f2d274ba18fc7b5345ee7353f.
