### ISSUE TITLE
More than one account under 1 dev account 

### ISSUE THREAD

**Issue by ddaddy** [nicolasgomollon/AppSales-Mobile#51]
I’ve just been added to another dev account and now I get an error saying “You have access to more than one account. Please specify an account number in your properties file or on the command line. To see a list of accounts, run the command getAccounts.”

Has anyone with multiple accounts on 1 dev account managed to get this working?

**Comment by nicolasgomollon** [comment]
Apologies for the delay! I’ve just implemented support for Apple IDs linked to multiple accounts in 2.5 (713) @ 95c026a8555d9b8c3bb0c74d604d883a9e37c78b, so this should now be fixed. Please let me know if it works properly for you.
