### ISSUE TITLE
app crash by "export reports"

### ISSUE THREAD

**Issue by tntechnology** [nicolasgomollon/AppSales-Mobile#53]
The program crashes when I exporting the reports. All reports are visible in the document folder, but "open in" does not appear. Is there a problem with the compression as ZIP?
I use Xcode 11.4.1 with iPhone 11 and the current version of AppSales 2.4.5 (711).

The following error message appears in the console after the crash:
Terminating app due to uncaught exception 'NSInternalInconsistencyException', reason: 'Modifications to the layout engine must not be performed from a background thread after it has been accessed from the main thread.'

What could be the reason?
Thanks for your help!

**Comment by nicolasgomollon** [comment]
I just merged in #48, so this should now be fixed. Please let me know if this is fixed in the latest commit.
