### ISSUE TITLE
Do Access Tokens still exist?

### ISSUE THREAD

**Issue by fixups** [nicolasgomollon/AppSales-Mobile#56]
I love AppSales. I have just downloaded and compiled the latest version.

My last access token has expired a few days ago, and I'm trying to refresh it.

AppSales cannot fetch any access token anymore. When you go, as advised, to **App Store Connect** > **Sales and Trends**, there is no **Reports** section anymore in which you could find the **(?)** button and get an Access Token from.

There is a **Reports** page accessible from **Sales and Trend**, but there is no access token to be found there either.

It looks like you now have, from the **App Store Connect** page, to go to **Users and Access**, and there you can generate "Keys" for various uses, and download them. I have generated one to get access to sales reports, but what I get is a ".p8" file that doesn't look like anything AppSales can digest.

I'm not sure if this page
  https://developer.apple.com/documentation/appstoreconnectapi/generating_tokens_for_api_requests
is relevant. I can't see a date on this page, so I don't now if it's new stuff or what. Anyway, they talk about a 20 minutes expiration time, so it looks like these tokens would have to be generated by AppSales on the fly.

Is it correct that Access Tokens are now obsolete? In this case, AppSales is going to break for everyone after their current Access Token expires.

**Comment by nicolasgomollon** [comment]
Hey @fixups,

I had fixed Access Token fetching/generating about a month ago. I also just tried using the Auto-Fill Wizard, and it properly fetched all values for me. Are you getting some kind of error in the app when you try this, or a message output in your console while running via Xcode? Also, what version of iOS are you using?

I am also able to view and generate a Reporter Token from App Store Connect at the following path:
App Store Connect → Sales and Trends → Sales and Trends Reports _(in the left hand sidebar)_ → About Reports (?) _(in the top right)_

The following link should also take you to the right place, where you can see the question mark icon next to the words “About Reports” in the top right corner of the page. From there, you should see an option to “Generate Reporter Token”, where you can view your existing token or generate a new one.
https://appstoreconnect.apple.com/trends/reports

Please let me know if you’re still having trouble.

**Comment by fixups** [comment]
Hi @nicolasgomollon 


Thank you for your reply. You nailed it. I was just looking in the wrong place for the "Generate Report Token" link.

All is good now, I have been able to generate a Report Token and AppSales has been able to fetch it.

Apple has changed the "Sales and Reports" page. It would great if you updated the help dialog that appears when AppSales cannot get a new token. It doesn't help that App Store Connect is displayed in French for me, so I have to translate back to English and try to guess what the original label was. :)

Also, I think we should erect a statue for the genius at Apple who thought that it was a good idea to hide the "Generate Report Token" link behind the question mark of "About reports". I have heard that a number of statue bases have gone vacant lately in Europe and the USA. :)

Just for reference, because it's pointless now, I'm using AppSales 2.5 (740) compiled with Xcode 11.5 (11E608c) under macOS 10.15.5. I'm running AppSales on an iPhone XR under iOS 13.5.1. I should have mentioned all of this in my previous message.

Thank you for answering so quickly on a Saturday evening, and most of all thank you for your work on AppSales.

What is the best way to show my appreciation for your work? Do you accept donations?


// Christophe

**Comment by sirnacnud** [comment]
My token just expired and the AutoFill Wizard doesn't work for me. I get "Cannot fetch CSRF token from server. Please try again later." error.

**Comment by ddaddy** [comment]
I've just tried to fix the AutoFill Wizard, but it seems there is no `CSFR` any more in the `/gsf/owasp/csrf-guard.js` response.
I'm not sure who originally sniffed the pages for this.

I've tried to proxy Appstore connect but it seems Apple have created some magic and none of the traffic goes through my proxy.

**Comment by nicolasgomollon** [comment]
I’ve fixed the CSRF token generation in a0eead2d93605eaccc1a46a4926807d67879b00c and updated the error message in fb2916419aea889c02fc7577e42881637d58b19c. Thanks everyone for your patience!

Please let me know if you’re still having issues generating or fetching your access token within the app after updating to the latest build.
