### ISSUE TITLE
Provider ID ?

### ISSUE THREAD

**Issue by demodit** [nicolasgomollon/AppSales-Mobile#59]
I'm still on version 2.4.5 because can't get version 2.5 to work.
Version 2.5 needs a Provider ID. Even Google search doesn't know about a iTunes Connect Provider ID. So I filled same ID as the Vendor ID. Is that correct ? Or where can the Provider ID be found ? 
Auto-Fill doesn't work for me, because I don't get any Verification Code on my devices.

When downloading report following message appears:
_Invalid account number specified. To see a list of accounts, run the command getAccounts._

**Comment by ddaddy** [comment]
I came here to tell you how to find your Provider ID, but after 30 minutes searching, I cannot find it anywhere in the dev portal!
Mine starts with 119 but the number is shown nowhere online.
Even when you fetch your Provider ID, i'm not sure the app will work without your verification code, so maybe look at fixing whatever issue is causing you not to receive the verification codes.

**Comment by demodit** [comment]
Thank you ddaddy. 
I have now managed to get a verification code. I had to sign in to iCloud with the same email address that is used to sign in to iTunes Connect. Provider ID no could be auto-filled.
