### ISSUE TITLE
NavigationBar messed up

### ISSUE THREAD

**Issue by ddaddy** [nicolasgomollon/AppSales-Mobile#61]
Building with Xcode 13.3 causes the Navigation bar to be black.
It happened with one of my apps, but I was in the process of a SwiftUI rewrite so never fixed it.
I don't have the time right now to look into it, but if anyone fancies a go?

![IMG_4511](https://user-images.githubusercontent.com/1425808/171392364-5ba3e9d8-65da-4d1f-8b84-e3b3d7db8e9a.jpg)

**Comment by Morpheus2002** [comment]
Same here. Already tried to find the issue but with no success now. It looks like some mess up with dark/light mode to me.

**Comment by ddaddy** [comment]
It’s due to a change in the nav bar appearance:
https://developer.apple.com/documentation/technotes/tn3106-customizing-uinavigationbar-appearance

https://developer.apple.com/forums/thread/682420

**Comment by ddaddy** [comment]
Fixed with PR #63
