### ISSUE TITLE
Figures changed today.

### ISSUE THREAD

**Issue by ddaddy** [nicolasgomollon/AppSales-Mobile#7]
Has anyone else's figures magically changed this morning?
I mean all my previously downloaded reports are now reporting super high incomes.

**Comment by Morpheus2002** [comment]
Same for me.

**Comment by ddaddy** [comment]
Wahoo, we're all rich. Apple gave us a bonus.

**Comment by Morpheus2002** [comment]
Just checked my stats again. It looks like the numbers are wrong only for several countries. In my case Russia, Japan, India, Indonesia has wrong numbers. All other countries like US, UK, Germany etc. are fine. 
I suppose something is wrong with currency conversion.

**Comment by ddaddy** [comment]
I'm having one of those 'How did this ever work' moments here.

If i'm reading this correctly, it is always and has always converted to EUR regardless of the currency set?

```
NSMutableDictionary *newExchangeRates = [NSMutableDictionary dictionary];

    [newExchangeRates setObject:@(1.0) forKey:@"\"EUR/EUR\""];

    NSMutableString *urlString = [NSMutableString stringWithString:@"https://download.finance.yahoo.com/d/quotes.csv?s="];
    int i = 0;
    for (NSString *currency in self.availableCurrencies) {
        if (i > 0) {
            [urlString appendString:@"+"];
        }
        if (![currency isEqual:@"EUR"]) {
            [urlString appendFormat:@"%@%@=X", currency, @"EUR"];
        }
        i++;
    }
    [urlString appendString:@"&f=nl1"];
```

Or does it just get the EUR conversion rates, then convert each rate to EUR, then convert the whole lot back to your currency?

**Comment by ddaddy** [comment]
Ok ignore that. It does in fact convert to a universal currency first.

**Comment by ddaddy** [comment]
Although it doesn't fix the problem. It is missing the Turkish Lira.
I can't make a pull request because I already have an open fork that if way behind this one.

If someone could fork, amend, and pull request the following?

In Classes/Model/CurrencyManager.m line 74 change to `@"THB", @"TRY", @"TWD",` and after line 133 add `[exchangeRates setObject:@(0.3058) forKey:@"\"TRY/EUR\""];`

Thanks

**Comment by ddaddy** [comment]
Never mind, I deleted my fork and forked this repo. I've made the change.
No for todays problem, if you press the country tab, you can see that it's Indonesia causing the problem.

**Comment by ddaddy** [comment]
I think we have to sit this one out and see if Yahoo fix it.
They have Indonesia currency returning a rate of `0.0652` when in fact the rate is `0.0000652` and Japanese Yen at `0.7741` when it should be `0.007741`.

So my 1 sale in Indonesia is reported as £2,500 :)

**Comment by ddaddy** [comment]
Anyone looking for a temporary fix, I have updated my fork here https://github.com/ddaddy/AppSales-Mobile

**Comment by nicolasgomollon** [comment]
Same issue here too. One sale in Indonesia apparently made me $1,500! I agree with @ddaddy, we should wait a couple of days to see if Yahoo fixes it, otherwise we can hard-code a fix that adjusts the decimal place for each of the incorrect countries. As a last resort, we can try to find another website that provides free exchange rates.

**Comment by nicolasgomollon** [comment]
It appears that the issue has fixed itself this morning, so it might have just been a temporary bug on Yahoo’s part. As a result, I’ll close this issue for now, but will reopen it if/when this bug occurs again, to explore other exchange rate options.
